sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential cmake libboost-system-dev libboost-thread-dev libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib

script:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake --version
  - cmake .
  - make
  - make test
